### ISSUE TITLE
environment variables field too small

### ISSUE THREAD

**Issue by AdriaandeJongh** [poohcom1/godot-run-configs#3]
Hey! The environment key value field is so small it's hard to see what I'm setting:

![Screenshot 2024-01-09 at 11 55 38](https://github.com/poohcom1/godot-run-configs/assets/5611323/eecf0878-c0a6-4f30-9152-d2b74ef13a0d)

**Comment by poohcom1** [comment]
I've updated the size from 150 to 200 px:

![image](https://github.com/poohcom1/godot-run-configs/assets/74857873/1e9cfb19-b812-4727-b82b-4be9c8b57a8b)

I'll update the addon on the library later, in the meantime you can update this line on your end if you want to change the size right now: https://github.com/poohcom1/godot-run-configs/blob/b74c9cc82b1894426731d566f666818bf98ffefd/addons/run-configs/editor/controls/configs_editor/env_editor.gd#L40


That said, based on your screenshot, it seems like your field looks much smaller than mine; it might be related to screen size. Either way, I'll increased it to 200px for now, let me know if it's still too small.

**Comment by AdriaandeJongh** [comment]
Perhaps make it proportional to the full width instead of a set pixel width? Like... 1/3rd of the full width maybe?

**Comment by poohcom1** [comment]
> Perhaps make it proportional to the full width instead of a set pixel width? Like... 1/3rd of the full width maybe?

There's probably a way to achieve that but I haven't looked into it. I assume most environment variable names shouldn't be too long anyway, so I just went with the faster solution to implement.

**Comment by AdriaandeJongh** [comment]
Well, 200 is still very small on my computer.

![Screenshot 2024-01-09 at 14 20 19](https://github.com/poohcom1/godot-run-configs/assets/5611323/7504bbc7-f8f2-435d-9652-a03585d48848)

Here's the fix:
1. add the following to _ready:
`grid_container.resized.connect(_on_resize)`
2. set the custom size to 1/3rd on start:
`key.custom_minimum_size.x = grid_container.size.x / 3`
3. add this function:
```
func _on_resize():
	var children = grid_container.get_children()
	for i in range(0, children.size(), 3):
		children[i].custom_minimum_size.x = grid_container.size.x / 3
```

this will make it look good at all times:

![Screenshot 2024-01-09 at 14 38 57](https://github.com/poohcom1/godot-run-configs/assets/5611323/deb94428-6da6-43e5-9d42-26863be0732f)

**Comment by poohcom1** [comment]
Looks good! If you want you can open a PR for this and I'll make an update to the asset library.
